=== Sowmya-Gandra/gardener-club/clubServer/applicantSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://homegarden.com/schemas/applicantdata",
    "title": "Applicant data collection",
    "descriptions": "A schema for applicant data",
    "type": "object",
    "properties": {
        "name": {
            "description":"Applicant name",
            "type": "string",
            "minimum":1,
            "maximum":50
        },
        "email": {
            "description":"member email",
            "type": "string",
            "format": "email"
        },
        "password":{
            "description":"password",
             "type":"string",
             "minlength":8,
             "maxlength":15
        },
        "know about us?":{
            "description": "survey",
                   "type": "array",
                   "items":{
                       "type":"string",
                       "enum": ["Facebook", "Advertisements", "Friends"]
                   }
        },
        "comments":{
            "description": "Comments or extra info from the applicant",
                   "type": "string",
              "maxLength": 400
        }
    },
    "required": ["name","email","password","know about us?","comments"],
    "additionalProperties": false

}

=== Sowmya-Gandra/gardener-club/clubServer/largeApplicant.json
[
 {
    "name": "samantha",
    "email": "saanthaexam711@yandex.com",
    "password":"password",
    "know about us?": ["Facebook"],
    "comments":"Something to learn that inspires!"
 },
 
    {
        "name": "sam",
        "email": "sameerasandesh931@yandex.com",
        "password":"password2",
        "know about us?": ["Advertisements"],
        "comments":"Something to learn!"
    },
{
      "name":"Gertude",
      "email":"althein1801@yahoo.com",
      "password":"password3",
      "know about us?": ["Advertisements"],
      "comments":"Something to learn!"

},
{
    "name":"Isidra",
    "email":"antonin2059@yahoo.com",
    "password":"password4",
    "know about us?": ["Advertisements"],
    "comments":"Something to learn!"

},


{
    "name": "gi yu ki",
    "email": "giyukipham658@yandex.com",
    "password":"password5",
    "know about us?": ["Advertisements"],
    "comments":"Love gardening!"

},

{
    "name": "eligebith",
    "email": "eligebithcampbell098@yandex.com",
    "password":"password6",
    "know about us?": ["Friends"],
    "comments":"my passion!"
},
{
    "name": "vladmir sudok",
    "email": "vladmir_sudok531@yandex.com",
    "password":"password7",
    "know about us?": ["Facebook"],
    "comments":"Something to analyze!"
},
{
   "name" : "Faustino",
   "email":"bayard1928@outlook.com",
   "password":"password8",
    "know about us?": ["Facebook"],
    "comments":"Something to analyze!"
}


]
