=== Sowmya-Gandra/gardener-club/clubServer/memberSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://homegarden.com/schemas/memberdata",
    "title": "Member data collection",
    "descriptions": "A schema for member data",
    "type": "object",
    "properties": {
        "firstName": {
            "description":"member firstname",
            "type": "string",
            "minlength":1,
            "maxlength":20
        },
        "lastName": {
            "description":"member lastname",
            "type": "string",
            "minlength":1,
            "maxlength":20
        },
        "email": {
              "description":"member email",
              "type": "string",
              "minlength":10,         
              "maxlength":30,
               "format":"email"    
        },
        "role":{
            "description": "member or not",
            "type": "string",
            "minlength":1,
            "maxlength":20,
            "enum": ["member","guest","admin"]
        },
        "password":{
            "description": "member secured details",
            "type": "string",
            "minlength":1,
            "maxlength":100 
        }
    },
    "required": ["firstName","lastName","email","role","password"],
    "additionalProperties": false
}

=== Sowmya-Gandra/gardener-club/clubServer/clubUsersHash.json
[
  {
    "firstName": "Melia",
    "lastName": "Barker",
    "email": "tirrivees1820@outlook.com",
    "password": "$2a$12$fEvJ7gczxeZnB2LXwuy9fOMpA6iPeWaXrLIQ70jRjJsm0qvnOw0ve",
    "role": "admin"
  },
  {
    "firstName": "Demetrice",
    "lastName": "Parker",
    "email": "chihuahua1899@gmail.com",
    "password": "$2a$12$sspnNWCMCV4fCSXNEF92lexsws/rGzCUutNcmvhD6EAvZk84zZE6.",
    "role": "member"
  },
  {
    "firstName": "Ligia",
    "lastName": "Hudson",
    "email": "umbrate1989@yahoo.com",
    "password": "$2a$12$etdKD8W.KJy00syWuSxGEuYHPlO0k9YTsu8HY.MHc2p5ZrMvS4LmO",
    "role": "member"
  },
  {
    "firstName": "Maisha",
    "lastName": "Hickman",
    "email": "bibiri1807@yandex.com",
    "password": "$2a$12$g8yWsG1HxgNitqTg5/CgK.nnbjcTJi5Cogghi23xwiAh/IEMbpyfi",
    "role": "member"
  },
  {
    "firstName": "Cythia",
    "lastName": "Park",
    "email": "biune1929@gmail.com",
    "password": "$2a$12$gPdItkFRmdSbQJVlzQQbtOE8tUx3PYpaTqQBXex/vBlITO0kdy46O",
    "role": "member"
  },
  {
    "firstName": "Arlie",
    "lastName": "Holt",
    "email": "aromatised1858@yandex.com",
    "password": "$2a$12$PN8e8a.iKz93ktQt5PQTJOzExGY5h.TVpKLv/cLQMK7lKv.1tbV3K",
    "role": "member"
  },
  {
    "firstName": "Andy",
    "lastName": "Morton",
    "email": "bayesian1899@outlook.com",
    "password": "$2a$12$uy5U8hl4SLjDP/VS3Wozt./4/3w8Ll1a0T4xSnQJYFTpACjU40UBi",
    "role": "member"
  },
  {
    "firstName": "Peg",
    "lastName": "Gardner",
    "email": "earrings1987@yandex.com",
    "password": "$2a$12$gQl0xiGBfqdAGLau/kEr7ONYSM96sjwzDr40pLiMq2iUpQbo3Ja72",
    "role": "member"
  },
  {
    "firstName": "Noble",
    "lastName": "Wilder",
    "email": "facer1912@yandex.com",
    "password": "$2a$12$Fu1xQa5fFGhHe0Od38Cnceb1ZK7HUUZolfrHTeaVgIM2.OGovemFm",
    "role": "member"
  },
  {
    "firstName": "Willow",
    "lastName": "Trevino",
    "email": "nodes1883@yahoo.com",
    "password": "$2a$12$c7DUQye3nteq2QjkpwuQguWsok6Cu0aAYVJnmEa22.9CuCAvcjKeu",
    "role": "member"
  },
  {
    "firstName": "Corrinne",
    "lastName": "Curtis",
    "email": "boisset1829@live.com",
    "password": "$2a$12$UTV9VfKQpH6aasopUOUUGeHmf48U/vfSXVTURM.woVx6YLQBteqFm",
    "role": "member"
  },
  {
    "firstName": "Joseph",
    "lastName": "Brock",
    "email": "utilizer1910@live.com",
    "password": "$2a$12$qGKXZntMm506u/tgP93Bo.dOun2WFXa6DaEy.dwSFDH4tvpSWlRzO",
    "role": "member"
  },
  {
    "firstName": "Daron",
    "lastName": "Stevens",
    "email": "pedocalcic1982@outlook.com",
    "password": "$2a$12$Dw9WY9eazLtchjQuT5vUIunTkgXtVgtvaf0N8EMMdkvyBMJaooe0y",
    "role": "member"
  },
  {
    "firstName": "Anamaria",
    "lastName": "Grant",
    "email": "downtown1843@live.com",
    "password": "$2a$12$k0NzhqX6sM.Mvpo/9NdiLeLLSKiDNvZoCm/1QMW19Rf.z68vt9yN.",
    "role": "member"
  },
  {
    "firstName": "Leonard",
    "lastName": "Shepherd",
    "email": "thrower1972@yahoo.com",
    "password": "$2a$12$Rsa94wsQ9.9Ugntrh2Qeju4FkbIXPwx8AImcuM6Bx3cbxQLdgYmN.",
    "role": "member"
  },
  {
    "firstName": "Belia",
    "lastName": "Monroe",
    "email": "cranky1882@gmail.com",
    "password": "$2a$12$j81SBjt6klu69bqIdZT.huMDl7qkKMFO.lhKRzoTPkiCH4CxSHOfa",
    "role": "member"
  },
  {
    "firstName": "Stacey",
    "lastName": "Calderon",
    "email": "marsileaceae1910@gmail.com",
    "password": "$2a$12$CIm4kvdGpeL6wSF53NY7tOn2xs7pcfmIVuF2aueviwWG9RSVQo3EC",
    "role": "member"
  },
  {
    "firstName": "Bob",
    "lastName": "Fitzgerald",
    "email": "burin1898@yahoo.com",
    "password": "$2a$12$He9LVVm3HX7K9K4Jk7SI9ev16aOP4KNA5ZQ6Q8QgR6hKkB5w.u5K6",
    "role": "member"
  },
  {
    "firstName": "Albertina",
    "lastName": "Mclaughlin",
    "email": "drainpipe2041@yandex.com",
    "password": "$2a$12$kRhAe03.PjvKo4iddytTNetmW092qfvvuvpcImHrXnYNOmcV26.Ve",
    "role": "member"
  },
  {
    "firstName": "Marg",
    "lastName": "Carney",
    "email": "ventages2031@yahoo.com",
    "password": "$2a$12$N.xixdGy7rcYQoSBPATMZO8zgGg7NDwFKWG1tVWMWBoB8EFo1bp/q",
    "role": "member"
  },
  {
    "firstName": "Jeffery",
    "lastName": "Charles",
    "email": "zaffer1889@live.com",
    "password": "$2a$12$hPCBpiIoIo9mmKlVSao8LusjPvDtdN1keD0fi2iG./5IvE8CMvASC",
    "role": "member"
  },
  {
    "firstName": "Annett",
    "lastName": "Parsons",
    "email": "kurikata1944@yandex.com",
    "password": "$2a$12$YRtwyLBzPeJeuEsOVHgLd.FiEgkrNUzsIBYIFS7I9s0IgKiO/9kfi",
    "role": "member"
  },
  {
    "firstName": "Wilson",
    "lastName": "Sharpe",
    "email": "misunderstandable1916@live.com",
    "password": "$2a$12$F/FBmRZpc3yi2jOYBc9nj.nhUy8FxVFPQSisHwAOMT9/MK9GFtiLa",
    "role": "member"
  },
  {
    "firstName": "Gertude",
    "lastName": "Ewing",
    "email": "althein1801@yahoo.com",
    "password": "$2a$12$UhcwdrfEe/LuzWi9c90Km.1PpCmIEmvrepvgePzhCMrdSVTtcR.HC",
    "role": "member"
  },
  {
    "firstName": "Phil",
    "lastName": "Knowles",
    "email": "piscators1880@live.com",
    "password": "$2a$12$73sfMH6/0JhA3DhA4VT1POwqXqOKiJCRrJotKPNSiJUlOljEs9K8q",
    "role": "member"
  },
  {
    "firstName": "Catherina",
    "lastName": "Castillo",
    "email": "saltworker1892@live.com",
    "password": "$2a$12$dfrSfub1V.tIiD0op4VW9eIw7fsIzFxZp5KchbFmgDdR2w02gl/sS",
    "role": "member"
  },
  {
    "firstName": "Jim",
    "lastName": "Kennedy",
    "email": "speer2026@outlook.com",
    "password": "$2a$12$rnz7oDAjIFfSuM.xLOHnMu6w3.6q3fdeXLyWIGQ8WRA56JYVx2YpK",
    "role": "member"
  },
  {
    "firstName": "Tula",
    "lastName": "Stafford",
    "email": "devoir1853@live.com",
    "password": "$2a$12$zMJmkqNXhxSV4pLvIJof9.ZMHij3PA.F2dMhnbaqvY1J4XEA3S2DO",
    "role": "member"
  },
  {
    "firstName": "Rachell",
    "lastName": "Harding",
    "email": "article1896@outlook.com",
    "password": "$2a$12$VE/Vp9j1.0UnGPHzRqb5suC1UKW39cuJpV.j.LQh8TO7kHezOjRp6",
    "role": "member"
  },
  {
    "firstName": "Brandon",
    "lastName": "Monroe",
    "email": "article1821@live.com",
    "password": "$2a$12$l6J5syoVgiJxex9orB3sb.gXrN7f7Bd./EbXvqU1BnYRiANVrnlOa",
    "role": "member"
  },
  {
    "firstName": "Micha",
    "lastName": "Sanders",
    "email": "fewer1818@outlook.com",
    "password": "$2a$12$Qq7Rx9Q/TKRrlIPV99QuE.dTtuTDySWL1vfSTrwwUrZFG3bhSz.UW",
    "role": "member"
  },
  {
    "firstName": "Blake",
    "lastName": "Gray",
    "email": "occults1985@yandex.com",
    "password": "$2a$12$jo1NAqfaRDtVXDuW45oIIuvaRQ7ob827ujs98oWNtTDeLhVBBGK1S",
    "role": "member"
  },
  {
    "firstName": "Karren",
    "lastName": "Crosby",
    "email": "harborers2000@live.com",
    "password": "$2a$12$TWQJnIOCfOQbo8dbgf8F2ur4w3VHOVTV3izjDiBNgl8zrCboC3buG",
    "role": "member"
  },
  {
    "firstName": "Faustino",
    "lastName": "Morris",
    "email": "bayard1928@outlook.com",
    "password": "$2a$12$L1hSh1I6AjIix.N9bux6FepZsB7KZuPgOZVvFkf1UfwN5cR5meh9O",
    "role": "member"
  },
  {
    "firstName": "Claretta",
    "lastName": "Cummings",
    "email": "fish2004@gmail.com",
    "password": "$2a$12$bqyykEnTvuKmYo5sFey.WuvnGSVA1NDN9x1TDOtIPFFq7.2RO5BjG",
    "role": "member"
  },
  {
    "firstName": "Carmen",
    "lastName": "Phillips",
    "email": "geometry1853@live.com",
    "password": "$2a$12$Z.mG4qyFam6iKyCqRbjd.Op2OxRwg.YXJ7Xd7g7YUR3FyykPZWvVG",
    "role": "member"
  },
  {
    "firstName": "Pamula",
    "lastName": "Holt",
    "email": "amperage1914@yandex.com",
    "password": "$2a$12$7eR6Ox3X4XDvWDMi3US5ReDXFWL.yTF5UgSR4NL2.WAMIyAKN7Yaq",
    "role": "member"
  },
  {
    "firstName": "Truman",
    "lastName": "Boyd",
    "email": "dustman2024@live.com",
    "password": "$2a$12$06/SX6mKu12q46jkKSyxb.kgQFyLmHRsktf3N4AKTQ/yeAgtRetgG",
    "role": "member"
  },
  {
    "firstName": "Alphonso",
    "lastName": "Salazar",
    "email": "raddle2043@yandex.com",
    "password": "$2a$12$C5zxOGujrTQsoc2ZyHDR.eyXbqSCw7hJgPkbxim5cTjp0OJWx0JMC",
    "role": "member"
  },
  {
    "firstName": "Isidra",
    "lastName": "O'neal",
    "email": "antonin2059@yahoo.com",
    "password": "$2a$12$jL.EZPbKxuzwz7boMXcOE.BgPILO.Pvmj1MM6D25cjzSh6XReX2Ty",
    "role": "member"
  }
]
